### ISSUE TITLE
ModuleNotFoundError: No module named 'seeding'

### ISSUE THREAD

**Issue by Saibo-creator** [derlin/swisstext-lrec#1]
Hello, I'm trying to reproduce your corpus scraping as described in the paper (LREC, 2019): Automatic Creation of Text Corpora for Low-Resource Languages from the Internet: The Case of Swiss German. I ran into the following error :

### To reproduce:

- Do installation steps following the readme of repo https://github.com/derlin/swisstext-lrec#installation

- Create a txt file under `swisstext-lrec/` named “swiss-german-sentences.txt” and paste the following text into it. `vim swiss-german-sentences.txt`
`Bettwanze und Vire im Gepäck Vorsorg Wer jetzt sini Sommerferie buecht, sött a möglichi unerwünschti Gescht dänke:
Epidemie, Wire und Wanze sind im Vormarsch.
Villi buechet jetzt Griechäland wäge de günschtige Agebot.
Doch Achtung:
Uf de Website Savetravel.ch warnt es Expertekomitee vor ere neue Tollwuet-epidemie.
Tollwuet wird dur de Speichel vo infizierte Säugetier( Hünd, Chatze, Nagetier und Flädermüüs) wiitergäh.
Tollwuet isch, wänn nüd rächtzytig behandlet, tödlich.
Drum impfe lah.
Wer liäber Richtig Asie flügt, söt abkläre, wie s ums neue« Chikungunya Fiäber» staaht.
Das wird vor allem us Indonesie, Bali, Java, Sumatra und Singapur gmäldet.
In Ostjakarta sind rund 200 Fäll regischtriert wordä.
än Impfschtoff gits no keine.
Typischi Symptom sind Glänkschmerzä i de Chnü und Chnöchel.
Dezue chömet typischi Grippe-symptom wie Temperatur, Kopfweh und Bindehutentzündig.
Fans vo Kuba söttet sich vor de Cholera in Acht neeh.
Suscht tanzt d Krankheit plöztli Samba im Organismus.
Es Souvenir, wo me guet chönnt verzichte.
Ufpasse sött me au im arabischä Ruum.`

- Try generating some seeds` python src/seeding/random_generator.py -i swiss-german-sentences.txt -o seeds.txt`, it gives

```
Traceback (most recent call last):
  File "src/seeding/random_generator.py", line 5, in <module>
    from seeding.generator_base import GeneratorBase
ModuleNotFoundError: No module named 'seeding'
```

**Comment by Saibo-creator** [comment]
I fix that by changing the import command: `vim src/seeding/random_generator.py`, replace at line 5, ` from seeding.generator_base import GeneratorBase` by `from generator_base import GeneratorBase`

**Comment by derlin** [comment]
I admit that the project was first meant to be installed with setuptools, hence the `src` folder. However, I got some troubles with the requirements, requiring pip and not setuptools to properly install. Anyway, a very easy fix is simply to run 

    export PYTHONPATH=$PWD/src

before running the script. I will update the readme accordingly.

**Comment by derlin** [comment]
updated readme in commit 7a625b9565301544de93d69b37cde0f1de2e0d8a.
