### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by Saibo-creator** [derlin/swisstext-lrec#2]
Hello, I'm trying to reproduce your corpus scraping as described in the paper (LREC, 2019): Automatic Creation of Text Corpora for Low-Resource Languages from the Internet: The Case of Swiss German. When running `python src/seeding/random_generator.py -i swiss-german-sentences.txt -o seeds.txt` I got into this error :

```
Traceback (most recent call last):
  File "src/seeding/random_generator.py", line 5, in <module>
    from generator_base import GeneratorBase
  File "/home/ubuntu/SwissCrawl/reprod_pymongo.errors/swisstext-lrec/src/seeding/generator_base.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

I have activated venv environment as mentioned in the doc. I just `pip install pandas` to fix this issue.

**Comment by derlin** [comment]
Hi, thank you for your interest!
I will look at your issues (and fix them) asap. Should get back to you in a few hours.

**Comment by derlin** [comment]
Everything under seeding is in a way optional, so I didn't include its dependencies in the `requirements.txt`. I thought the error would be clear enough for users to run `pip install pandas`. I will still add a note in the readme.

Thanks for reporting !
