### ISSUE TITLE
Data request email is no longer active

### ISSUE THREAD

**Issue by AmitMY** [derlin/swisstext-lrec#4]
In this page https://icosys.ch/swisscrawl
the "send us a request" email link is no longer valid.
> Your message wasn't delivered to claudiu.musat@swisscom.com because the address couldn't be found, or is unable to receive mail.

**Comment by derlin** [comment]
Hello there!
I have notified icosys already and am still waiting for an answer on their part, I will keep you posted!

**Comment by AmitMY** [comment]
Thanks! In the meanwhile, is there anyone else to "send a request" to?

**Comment by derlin** [comment]
The mail address has been updated on the website.
